pik-piam/lucode2

.buildlibrary, .zenodo.json, DESCRIPTION, R/buildLibrary.R, R/getFilesToLint.R, README.md
fixes #5 
With this PR only commits newer than the last version are considered for linting, without considering the last version commit itself.
=> Fix missing Date in DESCRIPTION error

.buildlibrary, .zenodo.json, DESCRIPTION, R/buildLibrary.R
ignore note about missing poorman package
=> update buildLibrary() to accept updateType = 0

.buildlibrary, .github/workflows/lucode2-check.yaml, .zenodo.json, DESCRIPTION, README.md, inst/extdata/lucode2-check.yaml
Create a package cache also when subsequent tests fail, speeding up iterative solving of test failures.
=> Always create package cache.

.buildlibrary, .github/workflows/lucode2-check.yaml, .zenodo.json, DESCRIPTION, README.md, inst/extdata/lucode2-check.yaml
Adds Python to github actions. Setting up python is unconditional because it is non-trivial to make it conditional and it takes 0s to do. Actually installing any Python dependencies only happens if there are Python dependencies.
=> Add Python to github actions

.buildlibrary, .zenodo.json, DESCRIPTION, R/addGitHubActions.R, R/buildLibrary.R, R/conditionalCopy.R, README.md
Changes:
* Automatically creates directories before trying to write configs into these directories (e.g. `.github/workflows`).
* Automatically creates `.gitignore` if it doesn't exist.
* Automatically adds `.github` to `.Rbuildignore` if it isn't included yet.
=> Create files and directories if they don't exist

.buildlibrary, .zenodo.json, DESCRIPTION, R/getScenNames.R, README.md, man/getScenNames.Rd, tests/testthat/test-getScenNames.R
Hi,
`getScenNames`' documentation was just plain lying, probably copied from `getModules`. I hope this is better.
Cheers,
Mika
=> Refactor getScenNames

.buildlibrary, .github/workflows/lucode2-check.yaml, .zenodo.json, DESCRIPTION, README.md, inst/extdata/lucode2-check.yaml, inst/extdata/rUniversePackages.json
Running our GitHub Action locally via act failed due to the caching, so I conditionally disabled it.
=> skip caching in local GHA

.buildlibrary, .zenodo.json, DESCRIPTION, R/manipulateConfig.R, README.md
Revert #122, it breaks REMIND.
=> Revert refactoring of manipulateConfig

.buildlibrary, .zenodo.json, DESCRIPTION, R/checkDeps.R, README.md
As discussed [here](https://github.com/remindmodel/remind/pull/1028#issuecomment-1286723280).
FYI: `checkDeps()` now returns a list of strings.
=> modify checkDeps() to warn, stop, or pass on unmet requirements

.buildlibrary, .zenodo.json, DESCRIPTION, R/checkDeps.R, README.md, man/checkDeps.Rd
Implements the feature requested in #127 
For this to be the most useful we should use `action = "ask"` in https://github.com/remindmodel/remind/pull/1030
=> add ask option for checkDeps

.Rbuildignore, .buildlibrary, .zenodo.json, DESCRIPTION, Makefile, R/buildLibrary.R, R/loadBuildLibraryConfig.R, README.md, inst/extdata/Makefile, inst/extdata/pre-commit-config.yaml, man/lucode2-package.Rd
Closes: #134 
* Adds a Makefile with commonly used commands in short form
* Also properly adds the .pre-commit-config.yaml so that it will be distributed asap.
=> Add Makefile, use new .pre-commit-config.yaml

.buildlibrary, .pre-commit-config.yaml, .zenodo.json, DESCRIPTION, README.md, inst/extdata/pre-commit-config.yaml
Latest versions for everything.
=> Update pre commit config

.buildlibrary, .zenodo.json, DESCRIPTION, R/eprint.R, R/readArgs.R, README.md, man/readArgs.Rd, tests/testthat/test-eprint.R, tests/testthat/test-readArgs.R
=> replace 'not found' by 'not defined' in readArgs to avoid that it looks like an error

.buildlibrary, .zenodo.json, DESCRIPTION, R/buildLibrary.R, R/package2readme.R, README.md, man/buildLibrary.Rd, man/package2readme.Rd
see [here](https://gitlab.pik-potsdam.de/lpjml/lpjmlkit/-/blob/metafile/README.md) for an example how this looks like
=> add option for buildLibrary to include package logo in readme

.buildlibrary, .zenodo.json, DESCRIPTION, Makefile, R/snakeToCamel.R, README.md, inst/extdata/Makefile, tests/testthat/test-snakeToCamel.R
snakeToCamel now also renames capitalized variables (`Variable` to `variable`) and does the right thing more often.
=> improve snakeToCamel

.buildlibrary, CITATION.cff, DESCRIPTION, R/buildLibrary.R, R/checkRepoUpToDate.R, R/citationDoi.R, R/conditionalCopy.R, R/extract_arguments.R, R/manipulateConfig.R, R/mergestatistics.R, R/package2readme.R, R/packageInfo.R, R/readArgs.R, R/readRuntime.R, R/updateRepo.R, README.md, tests/testthat/test-checkRequiredPackages.R, tests/testthat/test-theOneAndOnlyTandFsymbolFixer.R
lintr 3.1 introduced an indentation linter, so lucode2 was not longer lint warning free. This PR fixes that.
=> fix indentation

.buildlibrary, CITATION.cff, DESCRIPTION, R/packageInfo.R, README.md
- in packageInfo show time since install in days also
- Give you an idea how much 1166625 minutes actually means…
- For < 24 hours, the scripts says 0 days, I think that is ok
Old:
```
Package: base
Installed version: 4.1.2
Last updated: 1166625 minutes ago
```
New last line:
```
Last updated: 1166625 minutes / 810 days ago
```
Old:
```
Package: remind2
Installed version: 1.134.4
Last updated: 363 minutes ago
```
New last line:
```
Last updated: 363 minutes / 0 days ago
```
=> in packageInfo show time since install in days also

.buildlibrary, .pre-commit-config.yaml, CITATION.cff, DESCRIPTION, R/incrementVersion.R, README.md, man/buildLibrary.Rd
freezing versions in pre-commit config should hopefully prevent annoying auto-update PRs, let's see (will need to update manually before building lucode2 in the future)
=> fix incrementVersion for R 4.4

.buildlibrary, CITATION.cff, DESCRIPTION, README.md, man/lucode2-package.Rd
as required for the PRISMA project
=> added affiliation and keyword

.buildlibrary, CITATION.cff, DESCRIPTION, R/buildLibrary.R, R/loadBuildLibraryConfig.R, R/package2readme.R, README.md, man/buildLibrary.Rd
- added argument "AutocreateCITATION" to .buildLibrary config file
- CITATION information in README is now first tried to be extracted from CITATION.cff
=> Added AutocreateREADME argument and changed citation extraction for README.md

.buildlibrary, CITATION.cff, DESCRIPTION, R/check.R, README.md
- **unset RENV_PATHS_ROOT during check**
- **build**
=> fix renv cleanup error during check

.buildlibrary, CITATION.cff, DESCRIPTION, R/snakeToCamel.R, README.md
- **snakeToCamel does not replace at the start of string**
- **also exclude x$variable**
- **build**
=> fix snakeToCamel replacing strings
