.zenodo.json
DESCRIPTION
R/buildLibrary.R
README.md

I'm always calling `lucode::buildlibrary()` from the console history, but mix up the `update_types`.  Named update types would save me a couple of package build per week ;)

add character string update_type parameters

---

.buildlibrary
.zenodo.json
DESCRIPTION
R/autoFormat.R
R/buildLibrary.R
R/getFilesToLint.R
R/lint.R
README.md

- remove auto-format question in buildLibrary
- show linterResults directly when running buildLibrary
- do not auto-format linter-warning-free files per default
- run linter after auto-formatting per default
- use styler's strict = FALSE -> leaves extra spaces/newlines for better readability intact

Better linter/auto-formatter workflow

---

.buildlibrary
.zenodo.json
DESCRIPTION
R/readRuntime.R
README.md

For coupled REMIND-MAgPIE runs there is a pdf produced showing the runtime of the models across iterations and scenarios. It also displays a short statistic about the runtimes. This PR adds the average runtime of each model across scenarios and iterations to the statistic section.

Add average runtime to pdf.

---

.buildlibrary
.zenodo.json
DESCRIPTION
R/checkup.R
README.md
man/checkup.Rd

Add warnings to report so they can be searched and examined even if they too long to be displayed (truncated by default).

add warnings to report

---

.buildlibrary
.zenodo.json
DESCRIPTION
R/eprint.R
R/readArgs.R
README.md
man/eprint.Rd
man/readArgs.Rd

This fixes something that annoyed me working on [remind PR #621](https://github.com/remindmodel/remind/pull/621): If no command line arguments are provided, `readArgs.R` prints an error message despite using `try`, because apparently using `paste` on `try` concatenates this error message to the other strings.
I changed `eprint.R` such that it checks whether determining the variable value gives a `try-error` object, and if `TRUE`, states that the variable was not found. This also allows for a better distinction between “nothing was found and therefore the variable is not set” and “the variable was set to an empty string“, an ambiguity introduced by [my lucode2 PR #62](https://github.com/pik-piam/lucode2/pull/62).
I also switched from `print` to `cat` to avoid the `[1]` being printed, and …

let eprint not print error message, but instead 'not found'

---

.buildlibrary
.zenodo.json
DESCRIPTION
R/checkRepoUpToDate.R
README.md

The automatic up to date check was not working when the remote was using https instead of ssh, this PR fixes that. Broken remotes created by the erroneous previous version are removed and then created correctly

fix https bug in auto check git repo up to date

---

.buildlibrary
.zenodo.json
DESCRIPTION
R/eprint.R
README.md

If an argument read with `readArgs("regionList")` from the command line is a vector, `eprint()` concatenates it in an unreadable way (example is from remind compareScenario logging):
```
regionList <- GLOregionList <- LAMregionList <- OASregionList <- SSAregionList <- EURregionList <- NEUregionList <- MEAregionList <- REFregionList <- CAZregionList <- CHAregionList <- INDregionList <- JPNregionList <- USA
```
This PR turns it into:
```
regionList <- GLO, LAM, OAS, SSA, EUR, NEU, MEA, REF, CAZ, CHA, IND, JPN, USA
```
Was probably caused by switching from `print` to `message` before.

bugfix in eprint, nice format if variable is a vector/list

---

.buildlibrary
.zenodo.json
DESCRIPTION
R/manipulateConfig.R
README.md
tests/testthat/test-manipulateConfig.R

bugfix in manipulateConfig (GAMS allows "/" in quoted comments but not in unquoted comments)
This fixes issue #88

bugfix in manipulateConfig

---

.buildlibrary
.pre-commit-config.yaml
.zenodo.json
DESCRIPTION
README.md
inst/extdata/pre-commit-config.yaml

Too many problems were caused. When we want to re-enable it, we need a better plan how to get our repos into shape than "let the next person to make a pull request / push to the repo figure it out".

Stop fixing line endings using pre-commit.ci.

---

.buildlibrary
.github/workflows/lucode2-check.yaml
.zenodo.json
DESCRIPTION
README.md
inst/extdata/lucode2-check.yaml

Add a cache action which caches `/usr/local/lib/R` to github actions. In my [tests](https://github.com/pik-piam/gms/pull/24) it was significantly faster with a hot cache:
Without caching: 8m 34s
With caching (and hot cache): 3m 37s
Let's see how it does here.

Cache R packages in github actions

---

.buildlibrary
.zenodo.json
DESCRIPTION
R/buildLibrary.R
README.md

At the end of buildLibrary(), the script asks for an update type. In case of a [fat-finger problem](https://en.wikipedia.org/wiki/Fat-finger_error) where a wrong value is entered, it breaks everything. As the whole buildLibrary() process can take some time, this PR enables that if entered value makes no sense, it simply asks again, giving you an infinite number of chances…
I also took out the `strsplit(identifier, ",")` part, as it makes no sense to allow multiple answers such as `1,2` here…

ask more than once for correct update type

---

.buildlibrary
.github/workflows/lucode2-check.yaml
.pre-commit-config.yaml
.zenodo.json
DESCRIPTION
R/check.R
R/lint.R
R/lucode2-package.R
R/packageInfo.R
R/updateRepo.R
README.md
inst/extdata/lucode2-check.yaml
inst/extdata/pre-commit-config.yaml
man/packageInfo.Rd
man/updateRepo.Rd

`lucode2::updateRepo` now writes more metadata (just like r-universe) to DESCRIPTION files which is consumed e.g. by renv. Also added the following pre-commit hooks:
-   id: parsable-R
-   id: deps-in-desc
-   id: no-browser-statement
-   id: no-debug-statement
-   id: readme-rmd-rendered
-   id: use-tidy-description (which is not working at the moment, but will hopefully be fixed soon)
-   id: check-added-large-files
args: ['--maxkb=100']
-   id: mixed-line-ending
`devtools` >= 2.4.4 requires additional system dependencies, they were added to the GitHub Action.

DESCRIPTION metadata & precommit hooks

---

.buildlibrary
.github/workflows/lucode2-check.yaml
.zenodo.json
DESCRIPTION
R/check.R
R/conditionalCopy.R
R/updateRepo.R
README.md
inst/extdata/lucode2-check.yaml
inst/extdata/rUniversePackages.json
tests/testthat/test-updateRepo.R

The mattermost bot we set up a while ago does not message us on erros, because updateRepo would always catch all errors. Now it will catch and collect all errors at first and then throw them before returning if there were any.

rewrite updateRepo to collect and throw errors

---

.buildlibrary
.zenodo.json
DESCRIPTION
R/lint.R
R/readArgs.R
README.md
man/lint.Rd
man/lucode2-package.Rd
man/readArgs.Rd
tests/testthat/test-readArgs.R

in REMIND start.R, start_bundle_coupled.R, we use command line flags such as `--test` or `--parallel` to influence the script behavior. Instead of reimplementing it each time, add it to readArgs: You can then add a `.flags` argument with something like `argv <- lucode2::readArgs(.flags = c(t = "--test", p = "--parallel"))` and if you add `-pt` or `-p -t` or `--parallel` or `--test` to the command line while starting the scripts, these are recognized and returned as a vector which can then be checked with `if ("--test" %in% argv)`.
It can substitute scripts such as [this part](https://github.com/remindmodel/remind/blob/3b9f369c4b5cd32d01e9c3e541b5dc4f2c9d0e4f/start.R#L174-L185) in start.R

add possibility for command line flags to readArgs

---

.buildlibrary
.zenodo.json
DESCRIPTION
README.md
inst/extdata/pre-commit-config.yaml

Hm, apparently, the new pre-commit config was not included in the release, which explains why we saw a lot of automatic merge requests all over our package universe. Unfortunate. Highlights that our mechanism for distributing these centrally managed files is still brittle.

Actually distribute new pre-commit config

---

.buildlibrary
.github/workflows/lucode2-check.yaml
.zenodo.json
DESCRIPTION
README.md
inst/extdata/lucode2-check.yaml
man/checkDeps.Rd

Some caches in github actions are broken (e.g. https://github.com/pik-piam/gms/actions/runs/3312621942/jobs/5469522390 ), and they won't fix itself as long as there is at least one pull request per week. The official documented way to invalidate caches is to change the cache key so it will automatically generate and use new ones, and the old ones will be evicted after one week automatically.
Therefore, prepend a version number to the cache key. That will invalidate caches in all packages on the next `buildLibrary()`, so will fix gms actions, and lead to longer check times in all packages for the first PR after the change. I think that is fine (doing something especially for gms sounds like a lot of complexity for little gain, just avoiding a one-time increase in check times in all …

Invalidate caches

---

R/checkDeps.R

I think people just want to press Enter and get the required upgrade instead of having to type `y`.

checkDeps.R: if action=ask, update missing requirements by default.

---

.buildlibrary
.zenodo.json
DESCRIPTION
Makefile
README.md
inst/extdata/Makefile

Installing Make on windows is surprisingly simple, but additionally installing sed and column is a lot of work. Do all the parsing of the help texts in the Makefile in R instead, to get rid of these implicit dependencies. Now, the Makefile uses R exclusively.
Only downside is that the width for the tabulation needs to be chosen manually in the sprintf call, but that's fine, I think.

Use R exclusively in Makefile to reduce dependencies

---

.buildlibrary
.zenodo.json
DESCRIPTION
R/lintrRules.R
README.md
man/lintrRules.Rd

This PR allows modifications to the set of linter rules in a `.lintr` file. This feature must not be used in the default configuration of a package unless it was discussed with RSE.

allow linter rules modification

---

.buildlibrary
.github/workflows/lucode2-check.yaml
.zenodo.json
DESCRIPTION
R/autoFormat.R
README.md
inst/extdata/lucode2-check.yaml

Github actions are  - again - persistently broken because some cache is broken, see e.g. https://github.com/pik-piam/mrcommons/actions/runs/3748016612/jobs/6364875349 .
Also do not parse settings in `lintr::lint` in `theOneAndOnlyTandFSymbolFixer`  because the lintr people deprecated lintr::with_defaults, but continue to use it themselves in `lintr::lint(…, parse_settings=TRUE)` - and we do not want to parse settings in tOAOTFSF, anyway.

Invalidate caches again

---

.buildlibrary
.zenodo.json
DESCRIPTION
Makefile
R/getPackageAuthors.R
R/sendmail.R
R/validkey.R
README.md
inst/extdata/Makefile

Hi,
Since our goal is to make entire packages linter free and well-formatted, I added Make targets to run the linter/formatter on all files, not only changed files.
Also, I ran `format-all` on lucode2 itself, since there were still some formatting issues in older files.
Cheers,
Mika

Add lint-all and format-all targets to the Makefile, run format-all on lucode2 itself

---

.buildlibrary
.github/workflows/check.yaml
.zenodo.json
DESCRIPTION
README.md
inst/extdata/check.yaml

We got a warning that we should update to the latest versions of the github actions that we use, see [here](https://github.com/tscheypidi/mrorganic/actions/runs/3996515727) for example. Could you verify that the new Python setup works @mikapfl ?

update github actions versions

---

.buildlibrary
.github/workflows/check.yaml
CITATION.cff
DESCRIPTION
README.md
inst/extdata/check.yaml

- alternative approach to https://github.com/pik-piam/lucode2/pull/184
- codecov is only run in the github action if there are non-dummy test files
- tested by creating https://github.com/pik-piam/mrremind/pull/437

conditional codecov

---

.buildlibrary
CITATION.cff
DESCRIPTION
R/isVersionUpdated.R
R/loadBuildLibraryConfig.R
README.md
inst/extdata/check.yaml
man/isVersionUpdated.Rd

Adds `isVersionUpdated` as a check to the Github workflow `check`. Produces a warning by default, if version has not been incremented. Setting `enforceVersionUpdate: yes` turns it into an error.  The check only runs on pull requests.

add isVersionUpdated to check workflow

---

.buildlibrary
CITATION.cff
DESCRIPTION
R/isVersionUpdated.R
README.md

This fix avoids errors in isVersionUpdated when a package is not found on RSE server.
Currently, there is a problem when a new package needs to pass buildLibrary in order to be published on the RSE server, but in order to pass the check, the reference version is expected from the RSE server.

handle package not found on RSE server in isVersionUpdated

---

.buildlibrary
.github/workflows/check.yaml
CITATION.cff
DESCRIPTION
README.md
inst/extdata/check.yaml

This PR fixes the following warning:
Annotations
1 warning
check
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

update github action to address node 16 deprecation note

---

.buildlibrary
CITATION.cff
DESCRIPTION
R/manipulateConfig.R
README.md
tests/testthat/test-manipulateConfig.R

- Try to fix #203
- Running manipulateConfig() on REMIND's `main.gms` file (with the default settings read from that file) leads to the substitutions below. Any occurence of a switch name followed by `=` is substituted, leading to completely unreadable and misleading comments, and also leading to [model fails](https://github.com/pik-piam/lucode2/issues/203).
- I suggest to only replace `variable = value` constructions that show up at the beginning of the line, not anywhere. 
- I am not certain whether this creates any negative effects somewhere else – whether there are possible intended uses of replacing code in the middle of the line.
- I first thought might cause problems [here](https://github.com/magpiemodel/magpie/blob/92e0505d7fe366573c38b6c13f5dd73505a8ddb1/scripts/start/extra/emulat …

adjust variable = value regexp in manipulateConfig to avoid false positives in comments

---

.buildlibrary
CITATION.cff
DESCRIPTION
R/package2readme.R
README.md

I did a minor modification to the way a logo is added to the `README.md`.
- The logo no comes before not after the title in the same line.
- I set not only the height but also the width
The `README` looks better now with logos with a wide aspect ratio (they got too large with a height of 139px) and multi-line package titles (they used to push the logo down too much).
There should be no changes in appearance if
- the logo has an aspect ratio below 300:139.
- the title fits on one line.
closes #208

Improve logo with multi-line title in README

---

.buildlibrary
CITATION.cff
DESCRIPTION
R/buildLibrary.R
R/package2readme.R
README.md
man/buildLibrary.Rd
man/package2readme.Rd

~~Sets maximum height and width for the logo in README instead of fixed values to avoid distortion.~~
Instead of maximum height and width (not supported by github markdowns), logos are inserted only giving the height (just like before the problematic #209). But this height can now be changed from its default value of 139 px if one sets `LogoHeightReadme` in `.buildlibrary`.

Avoid logo distortion

---

.buildlibrary
.github/workflows/check.yaml
CITATION.cff
DESCRIPTION
R/buildLibrary.R
R/isVersionUpdated.R
R/loadBuildLibraryConfig.R
README.md
inst/extdata/check.yaml
man/buildLibrary.Rd
man/isVersionUpdated.Rd

This allows for packages to skip test coverage as part of the Github workflow checks by setting `skipCoverage: yes` in `.buildlibrary`

add 'skipCoverage' option to build library config

---

.buildlibrary
CITATION.cff
DESCRIPTION
R/check.R
README.md
man/verifyLinter.Rd

I was irritated by the inverted interpretation of `allowLinterWarnings` inside `verifyLinter` so I changed it. This should improve readability and have no effect of the correct functioning of the function.

Improve clearity: Remove unnecessary inversion of logical

---

.buildlibrary
CITATION.cff
DESCRIPTION
R/citationDoi.R
R/package2readme.R
README.md
inst/extdata/README_template.md

Dear @tscheypidi,
lpjmlkit has just been published on [JOSS](https://doi.org/10.21105/joss.05447), so we would like to acknowledge this. 
Our minimum requirement would be to add the JOSS badge next to the other badges in the README.  
[Here is how it looks like](https://github.com/jnnsbrr/lpjmlkit/tree/joss_in_readme).  
That's what I created this PR for.  
It adds the badge but lucode2 seems to have issues in handling additional DOIs being added to the DESCRIPTION.  
Issues are:
* the order of joss doi and zenodo doi determine which doi is included in the `"CITATION.cff"` file (only one is included)
* without the fix in `"citationDOI.R"` the DOIs get mixed up in the CITATION section in the `"README.md"`
Now the question is would it make sense to add a citation for JOSS (e.g. bibtex file) …

include JOSS badge

---

.buildlibrary
.github/workflows/check.yaml
CITATION.cff
DESCRIPTION
R/buildLibrary.R
README.md
inst/extdata/check.yaml

This allows us to get rid of the "pre-commit ci" Github app which automatically creates PRs to update the .pre-commit-config.yaml in all our repos. We want only lucode2 to get these updates and then all our other packages get these via lucode2.

run pre-commit via github action

---

.buildlibrary
CITATION.cff
DESCRIPTION
R/manipulateConfig.R
README.md

we have a rule/check in magpie that tabs are no longer allowed. manipulateConfig was introducing tabs for long lines. With this PR spaces are added instead

replace tabs with spaces

---

.buildlibrary
.github/workflows/check.yaml
CITATION.cff
DESCRIPTION
README.md
inst/extdata/check.yaml

This PR speeds up PR builds by more than a minute if there are tests in the package and also makes coverage reporting reliable again:
* Fixes the previously broken coverage. Coverage data was not reliably uploaded anymore, as codecov requires an organization token or else a global GH token is used. The `covr::codecov` call uses an old API that does not support organization tokens and thus we have also used the global GH token. We now use the codecov upload action with our organization token. To enable this, I needed to add a custom report format. In case r-lib/covr#616 is merged, we could replace this.
* Limits coverage calc to main branches. We could simplify `check.yml` by introducing a separate `coverage-reporting.yml` that only execute coverage and only does so on the main branch. Not …

Fixes coverage reporting and limits it to main branches only
